name: lechalo
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pin_code_fields: ^7.3.0
  cupertino_icons: ^1.0.3
  url_launcher: ^6.0.10
  flutter_slidable: ^0.6.0
  geolocator_android: ^3.1.0
  flutter_rounded_date_picker: ^3.0.2
  syncfusion_flutter_datepicker: ^19.2.56
  intl:
  google_maps_flutter: ^2.0.6
  flutter_screenutil: ^5.0.0+2
  weekday_selector: ^1.0.0
  http: ^0.13.3
  image_picker: ^0.8.4
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.7
  animated_splash_screen: ^1.1.0
  flutter_share: ^2.0.0
  share: ^2.0.4
  places_service: any
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19
  rating_dialog: ^2.0.1
  in_app_review: ^2.0.3
  flutter_polyline_points: ^1.0.0
  flutter_local_notifications: any
  workmanager: ^0.5.0
  day_picker: 1.0.1
  geocoding: any
  flutter_cache_manager: ^3.3.0
  google_api_headers: ^1.3.0
  table_calendar: ^3.0.6









  #  flutter_date_pickers: ^0.2.4





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/monitoring.png
    - assets/road-trip.png
    - assets/ecommerce.png
    - assets/tourist.png
    - assets/slider background.png
    - assets/add image.png
    - assets/male.png
    - assets/female.png
    - assets/loginpage background.png
    - assets/signuppage background.png
    - assets/gallery.png
    - assets/camera.png
    - assets/forgotpassword background.png
    - assets/verification.png
    - assets/Car Ride.png
    - assets/Cab.png
    - assets/bike.png
    - assets/Goods.png
    - assets/find ride.png
    - assets/offer a ride.png
    - assets/user.png
    - assets/search ride.png
    - assets/fingerprint.png
    - assets/facility.png
    - assets/profile.png
    - assets/money.png
    - assets/continue.png
    - assets/secure ride.png
    - assets/idUpload.png
    - assets/taxi.png
    - assets/pets.png
    - assets/music.png
    - assets/passenger.png
    - assets/driver.png
    - assets/smoking.png
    - assets/chattiness.png
    - assets/send parcel.png
    - assets/pick parcel.png
    - assets/map.png
    - assets/uploadParcel.png
    - assets/autoRickshaw.png
    - assets/cab2.png
    - assets/deliveryTruck.png
    - assets/logisticsTruck.png
    - assets/layer.jpeg
    - assets/moverTruck.png
    - assets/whatsapp.png
    - assets/call.png
    - assets/menu.png
#    - assets/menu2.svg
#    - assets/notification.png
#    - assets/splash.jpg
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Franklin_Gothic
      fonts:
        - asset: fonts/Franklin Gothic Medium Cond Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
